export enum ChannelAdminPermission {
	POST = 'POST',
	MAKE_ADMIN = 'MAKE_ADMIN',
	EDIT_OTHERS_POST = 'EDIT_OTHERS_POST',
	CREATE_NEW_ADMIN = 'CREATE_NEW_ADMIN',
	EDIT_ADMINS_PERMISSIONS = 'EDIT_ADMINS_PERMISSIONS',
	DELETE_ADMIN = 'REMOVE_ADMIN',
	DELETE_POST = 'DELETE_POST',
}
