export enum PostSort {
	FIRST = 'FIRST',
	LAST = 'LAST',
	RATING = 'RATING',
	RATING_DAY = 'RATING_DAY',
	RATING_MONTH = 'RATING_MONTH',
	RATING_WEEK = 'RATING_WEEK',
	VIEW = 'VIEW',
	VIEW_DAY = 'VIEW_DAY',
	VIEW_MONTH = 'VIEW_MONTH',
	VIEW_WEEK = 'VIEW_WEEK',
}
