export enum Process {
	AUTH = 'AUTH',
	HOME_PAGE = 'HOME_PAGE',
	RE_ANNOUNCEMENT = 'RE_ANNOUNCEMENT',
	USER = 'USER',
	POST = 'POST',
	ANNOUNCEMENT = 'ANNOUNCEMENT',
	CHANNEL = 'CHANNEL',
	ADMIN = 'ADMIN',
}
